#define MyAppName "Plume"
#define MyAppVersion "1.2.0"
#define MyAppPublisher "Hugo Informatique"
#define MyAppExeName "Plume.exe"

[Setup]
AppId={{A2AF7453-3D4B-45EC-B8B4-3F30E9C17D89}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={localappdata}\Programs\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=..\..\dist\installer
OutputBaseFilename=Plume-Setup-{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Branded wizard: the same feather mark as the app, in the same monochrome
; palette, instead of Inno's stock blue artwork. Several sizes are listed so
; Inno picks the right one per DPI rather than upscaling the 164px bitmap on a
; HiDPI laptop. Generated by scripts/make_icons.py (assets/ is gitignored).
WizardImageFile=..\..\assets\wizard.bmp,..\..\assets\wizard-2x.bmp,..\..\assets\wizard-3x.bmp
WizardSmallImageFile=..\..\assets\wizard-small.bmp,..\..\assets\wizard-small-2x.bmp,..\..\assets\wizard-small-3x.bmp
; Inno 6 hides the welcome page by default in modern style -- which is exactly
; the page the large artwork appears on.
DisableWelcomePage=no
; One language, so don't open on a language picker.
ShowLanguageDialog=no
; Nothing to choose on the way in: the install location is fixed (per-user) and
; the only option worth asking about is the desktop icon.
DisableDirPage=yes
DisableReadyPage=yes
AppCopyright=© Hugo Informatique — MIT
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64
UninstallDisplayName={#MyAppName}
SetupIconFile=..\..\assets\plume.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
AppPublisherURL=https://github.com/hugoinformatique/Plume
AppSupportURL=https://github.com/hugoinformatique/Plume/issues
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription=Plume — dictée vocale locale
VersionInfoProductName={#MyAppName}

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "Créer une icône sur le Bureau"; GroupDescription: "Icônes supplémentaires:"; Flags: unchecked

; Texte du wizard : on parle du produit, pas de « ce programme ». Le reste
; vient du fichier de langue French.isl.
[Messages]
WelcomeLabel1=Installation de [name]
WelcomeLabel2=Plume transcrit votre voix en texte, directement sur ce PC.%n%nAucun enregistrement et aucun texte ne quitte la machine : le moteur de reconnaissance et son modèle sont installés avec l'application.%n%nVersion [name/ver].
FinishedHeadingLabel=Plume est prêt
FinishedLabel=L'installation est terminée.%n%nAppuyez sur Ctrl + Espace n'importe où dans Windows pour dicter : le texte se colle dans l'application où vous écrivez.
ClickFinish=Cliquez sur Terminer pour quitter l'installation.

[Files]
Source: "..\..\dist\Plume\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "Lancer {#MyAppName}"; Flags: nowait postinstall skipifsilent
